# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
 repositories:
   - repository: -single-block-of-code-to-provision-two-web-apps
     name: giri347/-single-block-of-code-to-provision-two-web-apps
     type: github
     endpoint: giri347
     

       
trigger:
- main

pool:
  vmImage: 'windows-latest'

stages:
  - stage: dev
    jobs:
      - job: dev
        steps:
          - task: TerraformInstaller@0
            inputs:
             terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'einfo-terraform'
              backendAzureRmResourceGroupName: 'sa1_test_eic_DevOpslearning'
              backendAzureRmStorageAccountName: 'store15529900'
              backendAzureRmContainerName: 'container1'
              backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV3@3
            inputs:
             provider: 'azurerm'
             command: 'validate'
  - stage: prod
    jobs:
      - job: prod
        
        steps:
          - task: TerraformInstaller@0
            inputs:
             terraformVersion: 'latest'
          - task: TerraformTaskV3@3
            inputs:
             provider: 'azurerm'
             command: 'init'
             backendServiceArm: 'einfo-terraform'
             backendAzureRmResourceGroupName: 'sa1_test_eic_DevOpslearning'
             backendAzureRmStorageAccountName: 'store15529900'
             backendAzureRmContainerName: 'container1'
             backendAzureRmKey: 'terraform.tfstate'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'einfo-terraform'
          - task: TerraformTaskV3@3
            inputs:
              provider: 'azurerm'
              command: 'apply'
              commandOptions: '-auto-approve'
              environmentServiceNameAzureRM: 'einfo-terraform'
  


      
 







